name: kaskazini
description: Kaskazini chat app by the Mfereji.io team.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

################################################################

  app_runner: ^2.1.2
  get_it: ^7.2.0
  flutter_screenutil: ^5.6.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.12
  auto_route: ^5.0.4

  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.0.17

  meta: ^1.8.0
  equatable: ^2.0.5

  dio: ^5.0.3
  json_annotation: ^4.8.0

  flex_color_scheme: ^6.1.2
  google_fonts: ^4.0.3
  formz: ^0.6.0

#######
  mfereji:
    path: ../../mfereji-dart

  dash_chat_2: ^0.0.15
  responsive_builder: ^0.7.0
################################################################

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_launcher_icons: "^0.12.0"

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/img/
    - assets/img/bottom_nav/
    - assets/img/login/



